<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PrintableBook.Updater</AssemblyName>
    <RootNamespace>PrintableBook.Updater</RootNamespace>
  </PropertyGroup>
</Project>
